---
- hosts: all #you can choose hosts development|stage or all

  gather_facts: yes

  user: vagrant

  tasks:
  - name: install common package
    apt: name={{ item }} state=latest
    with_items:
      - vim
      - git

  - name: install apache
    apt: name=apache2 state=present

  - name: enables bash colors
    lineinfile: dest=/home/vagrant/.bashrc regexp=/#force_color_prompt=yes/ line=force_color_prompt=yes


  handlers:
    - name: restart apache
      service: name=apache state=restarted

  sudo: True

- hosts: development #you can choose hosts development|stage or all

  gather_facts: yes

  user: vagrant

  tasks:
  - name: create virtual host
    copy: src=/vagrant/provisioning/templates/apache/devmarche.dev.conf
          dest=/etc/apache2/sites-available/devmarche.dev.conf
          owner=root group=root mode=644 backup=yes

  handlers:
    - name: restart apache
      service: name=apache state=restarted

  sudo: True

- hosts: stage #you can choose hosts development|stage or all

  gather_facts: yes

  user: vagrant

  tasks:
  - name: create virtual host
    copy: src=/vagrant/provisioning/templates/apache/devmarche.stage.conf
          dest=/etc/apache2/sites-available/devmarche.stage.conf
          owner=root group=root mode=644 backup=yes

  handlers:
    - name: restart apache
      service: name=apache state=restarted

  sudo: True
